CREATE DATABASE AB106
USE AB106

CREATE TABLE STUDENTS
(
ID INT,
[NAME] NVARCHAR(15)NOT NULL,
SURNAME VARCHAR(25)NULL DEFAULT 'XXX',
AGE INT CHECK(AGE>=18),
AVGPOINT FLOAT CHECK(AVGPOINT BETWEEN 0 AND 100)
)

INSERT INTO STUDENTS([NAME], SURNAME, AGE, AVGPOINT)
VALUES('Rauf','Dostuyev',19,66),
('Samir','Babashov',19,66),
('Kamil','Kharamanovh',19,66),
('Ulvi','Abdullazada',19,66)


SELECT *FROM STUDENTS WHERE AVGPOINT > 51;


SELECT *FROM STUDENTS WHERE AVGPOINT > 51 AND AVGPOINT < 90;


SELECT *FROM STUDENTS WHERE Name LIKE 'A%' AND Name LIKE '%i';
